### PR TITLE
ci: setup everything

### PR DESCRIPTION
**Pull request by ccoVeille**
- add .vale.ini to setup Vale tool

- .gitignore
    exclude imported Vale Packages

- .yamllint.yaml
    YAML validation, excluding imported Vale Packages

- add .editorconfig to define files format

- add .ecrc to validate files format against .editorconfig
  but, excluding imported Vale Packages

- Git hooks via pre-commit including:
    - typos
    - codespell
    - yamllint

- added following items to GitHub Actions:

    - yamllint
    - vale
    - typos
    - codespell
    - markdownlint-cli2
    - editorconfig-checker

### CODE REVIEW

**Comment by ccoVeille** [comment]
@alexvonme here is what I worked on and that could be reused for https://github.com/jargonLint/jargonLint

**Comment by ccoVeille** [comment]
hey @jason3s I'm pretty proud of what I set up here

please review

**Comment by Jason3S** [comment]
> hey @Jason3S I'm pretty proud of what I set up here
> 
> please review

@ccoVeille,

I'm not sure how I can help. `codespell` is not a project I have worked on.

**Comment by ccoVeille** [comment]
Thanks, no problem.

I initially wanted to add cspell, but the fact this is still not available, I'm afraid I cannot consider it for now

- https://github.com/streetsidesoftware/cspell/discussions/5751

**Pull request merged**
